//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Singer
    {
        public Singer()
        {
            this.Album = new HashSet<Album>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Album> Album { get; set; }
    }
}
